# Generated by Django 4.2.3 on 2023-08-01 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_rename_distict_case_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='user',
        ),
        migrations.AddField(
            model_name='case',
            name='case',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='form',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.person'),
        ),
    ]
