# Generated by Django 4.2.3 on 2023-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_case_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='info',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
