# Generated by Django 4.2.3 on 2023-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
