# Generated by Django 4.2.3 on 2023-07-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_driver_section_vehicle_institution_identity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='on_delete',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='on_delete',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='on_delete',
        ),
        migrations.RemoveField(
            model_name='section',
            name='on_delete',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='on_delete',
        ),
    ]
