# Generated by Django 4.2.3 on 2023-07-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_driver_on_delete_remove_identity_on_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='app.institution'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='app.vehicle'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='app.section'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='app.driver'),
        ),
    ]
