# Generated by Django 4.2.3 on 2023-07-30 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_identity_vehicle_remove_institution_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distict', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('sun_unit', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=25)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('flag', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
