# Generated by Django 4.2.3 on 2023-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
