# Generated by Django 4.2.3 on 2023-07-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='distict',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='sun_unit',
            new_name='sub_unit',
        ),
    ]
