# Generated by Django 4.2.3 on 2023-07-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
