# Generated by Django 4.2.3 on 2023-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='section',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
