# Generated by Django 4.2.3 on 2023-08-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.person'),
        ),
    ]
