# Generated by Django 4.2.3 on 2023-08-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_case_person_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='info',
            field=models.IntegerField(null=True),
        ),
    ]
